@startuml
!include <C4/C4_Container>
!include ./../../../../../sources/container_units/iam.puml
!include ./../../../../../sources/container_units/ow.puml
!include ./../../../../../sources/container_units/sc.puml
!include ./../../../../../sources/container_units/syngx.puml
!include ./../../../../../sources/container_units/ingress.puml
!include ./../../../../../sources/container_units/styles.puml

title Схема SBT (K8S - SC - IAM)

set_styles()

' Уровень системы (System)
Person(user, "Пользователь", "Использует систему через браузер")

' Контейнеры внутри системы
Container_Boundary(vm, "VM") {
    IAM_SC_App(iam)
    Syngx_SC_App(nginx)
}

Container_Boundary(k8s_sys, "K8S") {
    Ingress_K8S_App(ingress)
    Container(k8s, "k8s service SC BE", "", "LB")
    SC_App(sc)
}

' Отношения
Rel(user, iam, " ")
Rel(iam, nginx, " ")
Rel(nginx, ingress, " ")
Rel(ingress, k8s, " ")

Rel(k8s, sc, " ")

@enduml
