TopicsSearch:
  get:
    summary: Поиск топиков (единый список топиков на всю инсталляцию)
    tags:
      - Topics
    operationId: GetTopicsList
    parameters:
      - $ref: '../../common/params.yaml#/components/parameters/q'
      - $ref: '../../common/params.yaml#/components/parameters/page'
      - $ref: '../../common/params.yaml#/components/parameters/limit'
    responses:
      '200':
        $ref: './responses.yaml#/components/responses/TopicsListResponse'
      '400':
        $ref: '../../common/errors.yaml#/components/responses/BadRequest'
      '401':
        $ref: '../../common/errors.yaml#/components/responses/Unauthorized'
      '403':
        $ref: '../../common/errors.yaml#/components/responses/Forbidden'
      '404':
        $ref: '../../common/errors.yaml#/components/responses/NotFound'
      '500':
        $ref: '../../common/errors.yaml#/components/responses/ServerError'
RepoTopics:
  put:
    tags:
      - Topics
    summary: Метод обновления списка топиков репозитория
    operationId: PutRepoTopics
    parameters:
      - $ref: '../../common/params.yaml#/components/parameters/project_name'
      - $ref: '../../common/params.yaml#/components/parameters/repo_name'
      - $ref: './params.yaml#/components/parameters/topics'
    responses:
      '200':
        $ref: '../../common/success.yaml#/components/responses/OperationSuccess'
      '400':
        $ref: '../../common/errors.yaml#/components/responses/BadRequest'
      '401':
        $ref: '../../common/errors.yaml#/components/responses/Unauthorized'
      '403':
        $ref: '../../common/errors.yaml#/components/responses/Forbidden'
      '404':
        $ref: '../../common/errors.yaml#/components/responses/NotFound'
      '500':
        $ref: '../../common/errors.yaml#/components/responses/ServerError'
