RepoSonarSettings:
  parameters:
    - $ref: '../../common/params.yaml#/components/parameters/Tenant'
    - $ref: '../../common/params.yaml#/components/parameters/Project'
    - $ref: '../../common/params.yaml#/components/parameters/Repo'
  get:
    tags:
      - sonar
    summary: Get Sonar settings
    operationId: v3GetSonarSettings
    responses:
      '200':
        $ref: './responses.yaml#/components/responses/SonarSettingsGetResponse'
      '401':
        $ref: '../../common/errors.yaml#/components/responses/Unauthorized'
      '403':
        $ref: '../../common/errors.yaml#/components/responses/Forbidden'
      '404':
        $ref: '../../common/errors.yaml#/components/responses/NotFound'
      '500':
        $ref: '../../common/errors.yaml#/components/responses/ServerError'
  post:
    tags:
      - sonar
    summary: Create Sonar settings
    operationId: v3CreateSonarSettings
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/CreateOrUpdateSonarProjectRequest'
    responses:
      '201':
        $ref: './responses.yaml#/components/responses/SonarSettingsCreatedResponse'
      '400':
        $ref: '../../common/errors.yaml#/components/responses/BadRequest'
      '401':
        $ref: '../../common/errors.yaml#/components/responses/Unauthorized'
      '403':
        $ref: '../../common/errors.yaml#/components/responses/Forbidden'
      '404':
        $ref: '../../common/errors.yaml#/components/responses/NotFound'
      '409':
        $ref: '../../common/errors.yaml#/components/responses/Conflict'
      '500':
        $ref: '../../common/errors.yaml#/components/responses/ServerError'
  put:
    tags:
      - sonar
    summary: Update Sonar settings
    operationId: v3UpdateSonarSettings
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/CreateOrUpdateSonarProjectRequest'
    responses:
      '200':
        $ref: './responses.yaml#/components/responses/SonarSettingsUpdatedResponse'
      '400':
        $ref: '../../common/errors.yaml#/components/responses/BadRequest'
      '401':
        $ref: '../../common/errors.yaml#/components/responses/Unauthorized'
      '403':
        $ref: '../../common/errors.yaml#/components/responses/Forbidden'
      '404':
        $ref: '../../common/errors.yaml#/components/responses/NotFound'
      '500':
        $ref: '../../common/errors.yaml#/components/responses/ServerError'
  delete:
    tags:
      - sonar
    summary: Delete Sonar settings
    operationId: v3DeleteSonarSettings
    responses:
      '204':
        $ref: './responses.yaml#/components/responses/SonarSettingsDeletedResponse'
      '400':
        $ref: '../../common/errors.yaml#/components/responses/BadRequest'
      '401':
        $ref: '../../common/errors.yaml#/components/responses/Unauthorized'
      '403':
        $ref: '../../common/errors.yaml#/components/responses/Forbidden'
      '404':
        $ref: '../../common/errors.yaml#/components/responses/NotFound'
      '500':
        $ref: '../../common/errors.yaml#/components/responses/ServerError'
