@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
!include ./../../../../../sources/deployment_units/spo/spo.puml
!include ./../../../../../sources/deployment_units/sc/sc.puml
!include ./../../../../../sources/deployment_units/actor/actor.puml
!include ./../../../../../sources/deployment_units/external/external.puml

'!include ./../../../../sources/C4_Deployment.puml
' Верхний уровень (сегменты)

AddElementTag("fallback", $bgColor="#c0c0c0")
AddRelTag("fallback", $textColor="#c0c0c0", $lineColor="#438DD5")
WithoutPropertyHeader()

Deployment_Node(segment0, "Компьютер пользователя", "Any") {
    Person_Deployment_Node(vm_user, user)
}

Deployment_Node(segment, "Периметр решения", "VM/K8S") {
    Deployment_Node(segment1, "Автоматизированная система SourceControl", "VM") {
        SourceControlFE_Deployment_Node(vm_product, fe, syngx)
        SourceControlCore_Deployment_Node(vm_product1, core)
        IAMProxy_Deployment_Node(vm_spo, proxy)
        Gitaly_Deployment_Node(vm_spo1, gitaly)
        Pangolin_Deployment_Node(vm_spo2, pangolin)
        Haproxy_Deployment_Node(vm_spo3, haproxy)
    }
    Deployment_Node(segment4, "Внешние системы", "VM/K8S") {
         Widget_Deployment_Node(ext_vm1, widget)
         TaskTracker_Deployment_Node(ext_vm2, tasktracker)
         CodeScanner_Deployment_Node(ext_vm3, codescanner)
         OneWork_Deployment_Node(ext_vm4, onework)
         Jenkins_Deployment_Node(ext_vm5, jenkins)
    }
    Deployment_Node(segment2, "Необязательное внешнее СПО", "VM/K8S", $tags="fallback") {
        Ngam_Deployment_Node(vm_spo4, "ngam")
        Corax_Deployment_Node(vm_spo5, corax)
        SecMan_Deployment_Node(vm_spo6, secman)
        SMTP_Deployment_Node(vm_spo7, smtp)
        LDAP_Deployment_Node(vm_spo8, ldap)
        Radish_Deployment_Node(vm_spo10, redis)
    }
}

Rel(user, proxy, "HTTPS", "v1.2")
Rel(user, haproxy, "HTTPS", "v1.2")
Rel(user, haproxy, "TCP")

Rel(core, pangolin, "TCP")
Rel(core, gitaly, "GRPC")
Rel(core, secman, "HTTPS", "v1.2")
Rel(core, corax, "TCP")
Rel(core, smtp, "SMTP")
Rel(core, ldap, "LDAP")
Rel(core, redis, "TCP")
Rel(core, widget, "HTTPS")
Rel(core, tasktracker, "MTLS", "v1.2")
Rel(core, codescanner, "HTTPS", "v1.2")

Rel(proxy, syngx, "HTTPS", "v1.2")
Rel(proxy, ngam, "HTTPS", "v1.2")

Rel(haproxy, core, "TCP")
Rel(haproxy, core, "HTTPS", "v1.2")

Rel(syngx, core, "HTTPS", "v1.2")
Rel(syngx, fe, "HTTPS", "v1.2")

SHOW_LEGEND()
@enduml