{
 "title": "SC Main Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "30s, 1m, 2m, 3m, 5m, 10m, 15m, 30m, 1h"
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_os_info{team=\"vcs\"},instance)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(sc_accesses,service)"
    }
   },
   {
    "name": "gitaly",
    "query": {
     "query": "label_values(gitaly_connections_total{team=\"vcs\", project=\"gitaly\"},instance)"
    }
   },
   { "name": "quantile", "query": "0.5, 0.75, 0.9, 0.95, 0.99, 1" }
  ]
 },
 "panels": [
  { "title": "Application. Storage Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество текущих выполняемых операций в s3-storage (in-flight)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (service, object_type, operation)(sc_static_storage_operations_in_progress{service=\"$service\",storage_type=\"s3\"})",
     "legendFormat": "Тип объекта: {{ object_type }} | Операция: {{ operation }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Время выполнение операций в S3-storage для заданного квантиля",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by (le, object_type, operation, service)(rate(sc_static_storage_operation_duration_seconds_bucket{storage_type=\"s3\"}[$rate])))",
     "legendFormat": "Тип объекта: {{ object_type }} | Операция: {{ operation }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Частота ошибок при взаимодействии с S3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (error_type,service,object_type,operation)(rate(sc_static_storage_errors_by_type_total{storage_type=\"s3\"}[$rate]))",
     "legendFormat": "Тип ошибки: {{ error_type }} | Тип объекта: {{ object_type }} | Операция: {{ operation }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Предположительное количество объектов в S3-хранилище",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (service, object_type)(sc_static_storage_objects_existence{service=\"$service\", storage_type=\"s3\"})",
     "legendFormat": "Тип объекта: {{ object_type }} | {{ service }}"
    },
    {
     "expr": "sum by (service)(sc_static_storage_objects_existence{service=\"$service\", storage_type=\"s3\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Общий объем объектов в S3-storage по типу объекта",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (object_type, service) (sc_static_storage_object_size_bytes_sum{service=\"$service\",storage_type=\"s3\"})",
     "legendFormat": "Тип объекта: {{ object_type }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Средний размер файла, загружаемого в S3-storage по типу объектов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (object_type, service) (rate(sc_static_storage_object_size_bytes_sum{service=\"$service\",storage_type=\"s3\"}[$rate])) / sum by (object_type, service) (rate(sc_static_storage_object_size_bytes_count{service=\"$service\",storage_type=\"s3\"}[$rate]))",
     "legendFormat": "Тип объекта: {{ object_type }} | {{ service }}"
    }
   ]
  },
  { "title": "Application. Redis Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Текущий backlog (необработанных) задач в очередях",
   "type": "timeseries",
   "description": "Если наблюдаем рост графика, то требуется исследование. Вероятно, воркеры не справляются с решением задач внутри очереди",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (queue, service) (sc_queue_items_enqueued_total{service=\"$service\"} - sc_queue_items_dequeued_total{service=\"$service\"}) >= 0 \n",
     "legendFormat": "{{ queue }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Скорость роста очередей задач",
   "type": "timeseries",
   "description": "Если график постоянно возрастает, то требуется исследование",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by (queue, service) (rate(sc_queue_items_enqueued_total{service=\"$service\"}[1m])) - sum by (queue, service) (rate(sc_queue_items_dequeued_total{service=\"$service\"}[1m]))",
     "legendFormat": "{{ queue }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Топ-5 очередей с наибольшим количеством задач",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sc_queue_items{type=\"redis\", service=\"$service\"})",
     "legendFormat": "{{ queue }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Процент загруженности workers по типу redis-очереди",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (queue,service) (sc_queue_workers_active{service=\"$service\"}) / sum by (queue,service) (sc_queue_workers{service=\"$service\"})",
     "legendFormat": "{{ queue }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Время выполнение единичной команды в Redis для заданного квантиля",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by (le,command)(rate(sc_redis_command_duration_seconds_bucket[$rate])) )",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Время установления TCP-соединения с Redis для заданного квантиля",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by (le, service, result, exported_instance)(rate(sc_redis_dial_duration_seconds_bucket[$rate])))",
     "legendFormat": "{{ exported_instance }} | {{ result }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Host. Утилизация CPU и RAM по хостам",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "Утилизация CPU по хостам",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{team=\"vcs\", mode=\"idle\"}[$rate])) by (instance,team,project))*100",
       "legendFormat": "{{ project }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "Утилизация RAM по хостам",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - \r\nnode_memory_MemAvailable_bytes{team=\"vcs\"} / node_memory_MemTotal_bytes{team=\"vcs\"} \r\n* 100",
       "legendFormat": "{{ project }} | {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host. Использование места на дисках по хостам",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "Использование места на дисках по хостам",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 301 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(\r\n100 - \r\nnode_filesystem_free_bytes{team=\"vcs\", fstype=\"ext4\"} \r\n/ \r\nnode_filesystem_size_bytes{team=\"vcs\", fstype=\"ext4\"} \r\n* 100\r\n)",
       "legendFormat": "{{ project }} | {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host. CPU подробнее",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"user\"}[$rate]) * 100) by (instance)",
       "legendFormat": "User | {{ instance }}"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"system\"}[$rate]) * 100) by (instance)",
       "legendFormat": "System | {{ instance }}"
      },
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"idle\"}[$rate])) by (instance))*100",
       "legendFormat": "Total | {{ instance }}"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"iowait\"}[$rate]) * 100) by (instance)",
       "legendFormat": "iowait | {{ instance }}"
      }
     ]
    },
    {
     "title": "Load Average хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$instance\"}",
       "legendFormat": "1m | {{ instance }}"
      },
      {
       "expr": "node_load5{instance=\"$instance\"}",
       "legendFormat": "5m | {{ instance }}"
      },
      {
       "expr": "node_load15{instance=\"$instance\"}",
       "legendFormat": "15m | {{ instance }}"
      },
      {
       "expr": " sum(count(node_cpu_seconds_total{instance=\"$instance\", mode='system'}) by (cpu,instance)) by(instance)",
       "legendFormat": "CPUs | {{ instance }}"
      }
     ]
    },
    {
     "title": "CPU по ядрам (Total) хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 285 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"idle\"}[$rate]) * 100",
       "legendFormat": "{{ cpu }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "CPU по ядрам (User) хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 285 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"user\"}[$rate]) * 100",
       "legendFormat": "{{ cpu }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "CPU по ядрам (System) хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 295 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"system\"}[$rate]) * 100",
       "legendFormat": "{{ cpu }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "CPU по ядрам (IOwait) хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 295 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"iowait\"}[$rate]) * 100",
       "legendFormat": "{{ cpu }} | {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host. RAM подробнее",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 275 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\"}",
       "legendFormat": "Available | {{ instance }}"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
       "legendFormat": "Total | {{ instance }}"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
       "legendFormat": "Free | {{ instance }}"
      },
      {
       "expr": "node_memory_Active_bytes{instance=\"$instance\"}",
       "legendFormat": "Active | {{ instance }}"
      },
      {
       "expr": "node_memory_Inactive_bytes{instance=\"$instance\"}",
       "legendFormat": "Inactive | {{ instance }}"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=\"$instance\"}",
       "legendFormat": "Shared | {{ instance }}"
      }
     ]
    },
    {
     "title": "Cache and Buffer хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 283 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Cached_bytes{instance=\"$instance\"}",
       "legendFormat": "Cached | {{ instance }}"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=\"$instance\"}",
       "legendFormat": "Buffers | {{ instance }}"
      }
     ]
    },
    {
     "title": "Slab хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 283 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Slab_bytes{instance=\"$instance\"}",
       "legendFormat": "Total | {{ instance }}"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{instance=\"$instance\"}",
       "legendFormat": "Slab Reclaimable | {{ instance }}"
      },
      {
       "expr": "node_memory_SUnreclaim_bytes{instance=\"$instance\"}",
       "legendFormat": "Slab Unreclaim | {{ instance }}"
      }
     ]
    },
    {
     "title": "Swap memory хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 292 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapCached_bytes{instance=\"$instance\"}",
       "legendFormat": "Cached | {{ instance }}"
      },
      {
       "expr": "node_memory_SwapFree_bytes{instance=\"$instance\"}",
       "legendFormat": "Free | {{ instance }}"
      },
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"}",
       "legendFormat": "Total | {{ instance }}"
      }
     ]
    },
    {
     "title": "Swap pages хоста ${instance}: ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 292 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(node_vmstat_pgmajfault{instance=\"$instance\"}[$rate])",
       "legendFormat": "Major page faults | {{ instance }}"
      },
      {
       "expr": "rate(node_vmstat_pgfault{instance=\"$instance\"}[$rate])",
       "legendFormat": "Total page faults | {{ instance }}"
      },
      {
       "expr": "rate(node_vmstat_pswpin{instance=\"$instance\"}[$rate])",
       "legendFormat": "Pages in | {{ instance }}"
      },
      {
       "expr": "rate(node_vmstat_pswpout{instance=\"$instance\"}[$rate])",
       "legendFormat": "Pages out | {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host. Использование места на дисках подробнее",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Использование места дисков хоста ${instance:value}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 276 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - \r\nnode_filesystem_free_bytes{instance=\"${instance}\", fstype=\"ext4\"} \r\n/ \r\nnode_filesystem_size_bytes{instance=\"${instance}\", fstype=\"ext4\"} \r\n* 100",
       "legendFormat": "{{ mountpoint }} | {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application. Количество сущностей",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество сущностей",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "sum by (service) (sc_accesses{service=\"$service\"})",
       "legendFormat": "Accesses | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_actions{service=\"$service\"})",
       "legendFormat": "Actions | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_comments{service=\"$service\"})",
       "legendFormat": "Comments | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_attachments{service=\"$service\"})",
       "legendFormat": "Attachments | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_follows{service=\"$service\"})",
       "legendFormat": "Follows | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_hooktasks{service=\"$service\"})",
       "legendFormat": "Hooktasks | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_issues{service=\"$service\"})",
       "legendFormat": "Issues | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_issues_closed{service=\"$service\"})",
       "legendFormat": "Issues_closed | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_issues_open{service=\"$service\"})",
       "legendFormat": "Issues_open | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_labels{service=\"$service\"})",
       "legendFormat": "Labels | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_milestones{service=\"$service\"})",
       "legendFormat": "Milestones | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_mirrors{service=\"$service\"})",
       "legendFormat": "Mirrors | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_oauths{service=\"$service\"})",
       "legendFormat": "Oauths | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_organizations{service=\"$service\"})",
       "legendFormat": "Organizations | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_projects{service=\"$service\"})",
       "legendFormat": "Projects | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_projects_boards{service=\"$service\"})",
       "legendFormat": "Projects_boards | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_publickeys{service=\"$service\"})",
       "legendFormat": "Publickeys | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_releases{service=\"$service\"})",
       "legendFormat": "Releases | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_repositories{service=\"$service\"})",
       "legendFormat": "Repositories | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_stars{service=\"$service\"})",
       "legendFormat": "Stars | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_teams{service=\"$service\"})",
       "legendFormat": "Teams | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_updatetasks{service=\"$service\"})",
       "legendFormat": "Updatetasks | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_users{service=\"$service\"})",
       "legendFormat": "Users | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_watches{service=\"$service\"})",
       "legendFormat": "Watches | {{ service }}"
      },
      {
       "expr": "sum by (service) (sc_webhooks{service=\"$service\"})",
       "legendFormat": "Webhook | {{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application. Статистика успешных http запросов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 }
  },
  {
   "title": "Суммарная интенсивность успешных http запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "sum by (service)(rate(sc_http_request_handled_total{service=\"$service\", http_code=~\"^1..|^2..|^3..\"}[$rate]))",
     "legendFormat": "Total | {{ service }}"
    }
   ]
  },
  {
   "title": "Интенсивность успешных http запросов",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "sum by (service,method,path) (rate(sc_http_request_handled_total{service=\"$service\", http_code=~\"^1..|^2..|^3..\"}[$rate]))",
     "legendFormat": "{{ method }} {{ path }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Время обработки (AVG)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service,method,path) (rate(sc_http_request_duration_seconds_sum{service=\"$service\"}[$rate]) )\r\n/ \r\nsum by (service,method,path) (rate(sc_http_request_duration_seconds_count{service=\"$service\"}[$rate]))",
     "legendFormat": "{{ method }} {{ path }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Application. Статистика git-запросов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 }
  },
  {
   "title": "Суммарная интенсивность git-запросов",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "sum by (service)(rate(sc_git_request_duration_seconds_count{service=\"$service\"}[$rate]))",
     "legendFormat": "Total | {{ service }}"
    }
   ]
  },
  {
   "title": "Интенсивность git-запросов (ssh)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "sum by (service, protocol, operation) (rate(sc_git_request_duration_seconds_count{service=\"$service\",protocol=\"ssh\"}[$rate]))",
     "legendFormat": "{{ protocol }}: {{ operation }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Интенсивность git-запросов (https)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 150 },
   "targets": [
    {
     "expr": "sum by (service, protocol, operation) (rate(sc_git_request_duration_seconds_count{service=\"$service\",protocol=\"https\"}[$rate]))",
     "legendFormat": "{{ protocol }}: {{ operation }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Application. Статистика http запросов с ошибками",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 }
  },
  {
   "title": "Суммарная интенсивность http запросов с ошибкой",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 161 },
   "targets": [
    {
     "expr": "sum by (service) (rate(sc_http_request_handled_total{service=\"$service\", http_code!~\"^1..|^2..|^3..\"}[$rate]))",
     "legendFormat": "Total | {{ service }}"
    }
   ]
  },
  {
   "title": "Интенсивность http запросов с ошибкой",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 169 },
   "targets": [
    {
     "expr": "sum by (service, method, path) (rate(sc_http_request_handled_total{service=\"$service\", http_code!~\"^1..|^2..|^3..\"}[$rate]))",
     "legendFormat": "{{ method }} {{ path }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Количество HTTP запросов с ошибкой",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service, method, path) (rate(sc_http_request_handled_total{service=\"$service\", http_code!~\"^1..|^2..|^3..\"}[$rate])) * 120 != 0",
     "legendFormat": "{{ method }} {{ path }} | {{ service }}"
    }
   ]
  },
  {
   "title": "Application. Go routines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 },
   "collapsed": true,
   "panels": [
    {
     "title": "go_goroutines",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (service) (go_goroutines{service=\"$service\"})",
       "legendFormat": "Total | {{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application. Go memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service) (go_memstats_sys_bytes{service=\"$service\"})",
       "legendFormat": "Total | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_heap_sys_bytes{service=\"$service\"})",
       "legendFormat": "Heap | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_stack_sys_bytes{service=\"$service\"})",
       "legendFormat": "Stack | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_mspan_sys_bytes{service=\"$service\"})",
       "legendFormat": "Span | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_mcache_sys_bytes{service=\"$service\"})",
       "legendFormat": "Cache | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_gc_sys_bytes{service=\"$service\"})",
       "legendFormat": "GC | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_other_sys_bytes{service=\"$service\"})",
       "legendFormat": "Other | {{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application. Go memory in Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 283 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service) (go_memstats_heap_sys_bytes{service=\"$service\"})",
       "legendFormat": "Total | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_heap_inuse_bytes{service=\"$service\"})",
       "legendFormat": "Used | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_heap_alloc_bytes{service=\"$service\"})",
       "legendFormat": "Allocated | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_heap_idle_bytes{service=\"$service\"})",
       "legendFormat": "Idle | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_heap_released_bytes{service=\"$service\"})",
       "legendFormat": "Released | {{ service }}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 292 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (service) (go_memstats_heap_objects{service=\"$service\"})",
       "legendFormat": "Total | {{ service }}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated / Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 292 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (service) (rate(go_memstats_mallocs_total{service=\"$service\"}[$rate]))",
       "legendFormat": "Allocated | {{ service }}"
      },
      {
       "expr": "sum by (service) (rate(go_memstats_frees_total{service=\"$service\"}[$rate]))",
       "legendFormat": "Free | {{ service }}"
      }
     ]
    },
    {
     "title": "Rate of Allocated bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 300 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service) (rate(go_memstats_alloc_bytes_total{service=\"$service\"}[$rate]))",
       "legendFormat": "Total | {{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application. Go memory out off Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 284 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service) (go_memstats_mspan_sys_bytes{service=\"$service\"})",
       "legendFormat": "Span | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_mcache_sys_bytes{service=\"$service\"})",
       "legendFormat": "Cache | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_buck_hash_sys_bytes{service=\"$service\"})",
       "legendFormat": "Buck hash | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_gc_sys_bytes{service=\"$service\"})",
       "legendFormat": "GC | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_other_sys_bytes{service=\"$service\"})",
       "legendFormat": "Other | {{ service }}"
      }
     ]
    },
    {
     "title": "Span",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 284 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service) (go_memstats_mspan_sys_bytes{service=\"$service\"})",
       "legendFormat": "Total | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_mspan_inuse_bytes{service=\"$service\"})",
       "legendFormat": "Used | {{ service }}"
      }
     ]
    },
    {
     "title": "Cache",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service) (go_memstats_mcache_sys_bytes{service=\"$service\"})",
       "legendFormat": "Total | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_mcache_inuse_bytes{service=\"$service\"})",
       "legendFormat": "Used | {{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application. Go memory in Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stack",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 285 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service) (go_memstats_stack_sys_bytes{service=\"$service\"})",
       "legendFormat": "Total | {{ service }}"
      },
      {
       "expr": "sum by (service) (go_memstats_stack_inuse_bytes{service=\"$service\"})",
       "legendFormat": "Used | {{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application. Go GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 },
   "collapsed": true,
   "panels": [
    {
     "title": "go_gc_duration_seconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 286 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (service, quantile) (go_gc_duration_seconds{service=\"$service\"})",
       "legendFormat": "{{ quantile }} | {{ service }}"
      }
     ]
    },
    {
     "title": "go_gc_duration (avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 286 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (service, quantile) (rate(go_gc_duration_seconds_sum{service=\"$service\"}[$rate])) \r\n/ \r\nsum by (service, quantile) (rate(go_gc_duration_seconds_count{service=\"$service\"}[$rate]))",
       "legendFormat": "{{ quantile }} | {{ service }}"
      }
     ]
    },
    {
     "title": "go_memstats_next_gc_bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 295 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (service, quantile) (go_memstats_next_gc_bytes{service=\"$service\"})",
       "legendFormat": "{{ quantile }} | {{ service }}"
      }
     ]
    },
    {
     "title": "go_memstats_last_gc_time_seconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 295 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - sum by (service) (go_memstats_last_gc_time_seconds{service=\"$service\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Gitaly. Количество репозиториев",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество репозиториев",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 287 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "gitaly_total_repositories_count{instance=\"$gitaly\", prefix=\"var\"}",
       "legendFormat": "{{ path }} | {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gitaly. Статистика git-запросов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 191 },
   "collapsed": true,
   "panels": [
    {
     "title": "Суммарная интенсивность git-запросов",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 288 },
     "targets": [
      {
       "expr": "rate(gitaly_git_protocol_requests_total{instance=\"$gitaly\",grpc_service=\"gitaly.SSHService\"}[$rate])",
       "legendFormat": "{{ grpc_service }}: {{ grpc_method }} | {{ instance }}"
      },
      {
       "expr": "rate(gitaly_git_protocol_requests_total{instance=\"$gitaly\",grpc_service=\"gitaly.SmartHTTPService\",grpc_method=\"InfoRefsUploadPack\"}[$rate])",
       "legendFormat": "{{ grpc_service }}: {{ grpc_method }} | {{ instance }}"
      },
      {
       "expr": "rate(gitaly_git_protocol_requests_total{instance=\"$gitaly\",grpc_service=\"gitaly.SmartHTTPService\",grpc_method=\"InfoRefsReceivePack\"}[$rate])",
       "legendFormat": "{{ grpc_service }}: {{ grpc_method }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "Интенсивность git-запросов (ssh)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 298 },
     "targets": [
      {
       "expr": "rate(gitaly_git_protocol_requests_total{instance=\"$gitaly\",grpc_service=\"gitaly.SSHService\"}[$rate])",
       "legendFormat": "{{ grpc_service }}: {{ grpc_method }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "Интенсивность git-запросов (https)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 298 },
     "targets": [
      {
       "expr": "rate(gitaly_git_protocol_requests_total{instance=\"$gitaly\",grpc_service=\"gitaly.SmartHTTPService\",grpc_method=\"InfoRefsUploadPack\"}[$rate])",
       "legendFormat": "{{ grpc_service }}: {{ grpc_method }} | {{ instance }}"
      },
      {
       "expr": "rate(gitaly_git_protocol_requests_total{instance=\"$gitaly\",grpc_service=\"gitaly.SmartHTTPService\",grpc_method=\"InfoRefsReceivePack\"}[$rate])",
       "legendFormat": "{{ grpc_service }}: {{ grpc_method }} | {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gitaly. gRPC-запросы",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 },
   "collapsed": true,
   "panels": [
    {
     "title": "Суммарная интенсивность gRPC-запросов",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "tps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{instance=\"$gitaly\"}[$rate]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Интенсивность gRPC-запросов",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "tps" } },
     "targets": [
      {
       "expr": "sum by (grpc_method, instance)(rate(grpc_server_started_total{instance=\"$gitaly\",}[$rate]))",
       "legendFormat": "{{ grpc_method }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "Интенсивность успешных gRPC-запросов",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "tps" } },
     "targets": [
      {
       "expr": "sum by (grpc_method, instance)(rate(grpc_server_handled_total{instance=\"$gitaly\",grpc_code=\"OK\"}[$rate]))",
       "legendFormat": "{{ grpc_method }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "Время обработки gRPC-запросов (AVG)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(grpc_server_handling_seconds_sum{instance=\"$gitaly\"}[$rate]) \r\n/ \r\nrate(grpc_server_handling_seconds_count{instance=\"$gitaly\"}[$rate])",
       "legendFormat": "{{ grpc_method }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "Количество активных (выполняющихся в данный момент) gRPC-запросов",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without(grpc_code) (grpc_server_started_total{instance=\"$gitaly\"}) \r\n- \r\nsum without(grpc_code) (grpc_server_handled_total{instance=\"$gitaly\"})",
       "legendFormat": "{{ grpc_method }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "Интенсивность gRPC-запросов с ошибкой",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "tps" } },
     "targets": [
      {
       "expr": "sum by (grpc_method, grpc_code, instance) (rate(grpc_server_handled_total{instance=\"$gitaly\", grpc_code!=\"OK\"}[$rate]))",
       "legendFormat": "{{ grpc_method }}: {{ grpc_code }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "Количество gRPC-запросов с ошибкой",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (grpc_method, grpc_code, instance)(rate(grpc_server_handled_total{instance=\"$gitaly\", grpc_code!=\"OK\"}[$rate])) * 120 != 0",
       "legendFormat": "{{ grpc_method }}: {{ grpc_code }} | {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gitaly. gRPC-сообщения",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 193 },
   "collapsed": true,
   "panels": [
    {
     "title": "Суммарная интенсивность принятых gRPC-сообщений",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "tps" } },
     "targets": [
      {
       "expr": "sum by (instance)(rate(grpc_server_msg_received_total{instance=\"$gitaly\"}[$rate]))",
       "legendFormat": "Принятые | {{ instance }}"
      },
      {
       "expr": "sum by (instance)(rate(grpc_server_msg_sent_total{instance=\"$gitaly\"}[$rate]))",
       "legendFormat": "Отправленные | {{ instance }}"
      }
     ]
    },
    {
     "title": "Интенсивность принятых gRPC-сообщений",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 300 },
     "fieldConfig": { "defaults": { "unit": "tps" } },
     "targets": [
      {
       "expr": "sum by (grpc_method, instance)(rate(grpc_server_msg_received_total{instance=\"$gitaly\"}[$rate]))",
       "legendFormat": "{{ grpc_method }} | {{ instance }}"
      }
     ]
    },
    {
     "title": "Интенсивность отправленных gRPC-сообщений",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 300 },
     "fieldConfig": { "defaults": { "unit": "tps" } },
     "targets": [
      {
       "expr": "sum by (grpc_method, instance)(rate(grpc_server_msg_sent_total{instance=\"$gitaly\"}[$rate]))",
       "legendFormat": "{{ grpc_method }} | {{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}