RepoExternalMetrics:
  parameters:
    - $ref: '../../common/params.yaml#/components/parameters/Tenant'
    - $ref: '../../common/params.yaml#/components/parameters/Project'
    - $ref: '../../common/params.yaml#/components/parameters/Repo'
  get:
    tags:
      - external_metrics
    summary: List external metrics
    operationId: v3ListExternalMetrics
    responses:
      '200':
        $ref: './responses.yaml#/components/responses/ExternalMetricsListResponse'
      '401':
        $ref: '../../common/errors.yaml#/components/responses/Unauthorized'
      '403':
        $ref: '../../common/errors.yaml#/components/responses/Forbidden'
      '404':
        $ref: '../../common/errors.yaml#/components/responses/NotFound'
      '500':
        $ref: '../../common/errors.yaml#/components/responses/ServerError'

RepoExternalMetric:
  parameters:
    - $ref: '../../common/params.yaml#/components/parameters/Tenant'
    - $ref: '../../common/params.yaml#/components/parameters/Project'
    - $ref: '../../common/params.yaml#/components/parameters/Repo'
    - $ref: '../../common/params.yaml#/components/parameters/Metric'
  post:
    tags:
      - external_metrics
    summary: Set external metric
    operationId: v3SetExternalMetric
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/SetExternalMetricRequest'
    responses:
      '201':
        $ref: './responses.yaml#/components/responses/ExternalMetricResponse'
      '400':
        $ref: '../../common/errors.yaml#/components/responses/BadRequest'
      '401':
        $ref: '../../common/errors.yaml#/components/responses/Unauthorized'
      '403':
        $ref: '../../common/errors.yaml#/components/responses/Forbidden'
      '500':
        $ref: '../../common/errors.yaml#/components/responses/ServerError'
  delete:
    tags:
      - external_metrics
    summary: Delete external metric
    operationId: v3DeleteExternalMetric
    responses:
      '204':
        $ref: './responses.yaml#/components/responses/ExternalMetricDeletedResponse'
      '400':
        $ref: '../../common/errors.yaml#/components/responses/BadRequest'
      '401':
        $ref: '../../common/errors.yaml#/components/responses/Unauthorized'
      '403':
        $ref: '../../common/errors.yaml#/components/responses/Forbidden'
      '404':
        $ref: '../../common/errors.yaml#/components/responses/NotFound'
      '500':
        $ref: '../../common/errors.yaml#/components/responses/ServerError'
