@startuml

!include <C4/C4_Container>
!include <C4/C4_Component>
!include ./../../../../../sources/component_units/sc.puml
!include ./../../../../../sources/component_units/service.puml
!include ./../../../../../sources/component_units/interface.puml
!include ./../../../../../sources/component_units/styles.puml
!include ./../../../../../sources/component_units/external_storages/redis.puml

title Детализированная диаграмма взаимодействия SourceControl c Platform V Radish

set_styles()

System_Boundary(sc, "SС Backend") {
    SC_Component_App(sc_app)

    Interface_SC(cache, "Cache", "Кеш приложения")
    Implementation_SC(cache_redis, "RedisCacher", "адаптер для установки редис кеша на уровне chi-кеша. Тут же инициализируется клиент redis")
    note left of cache_redis
        Использует конфигурационные параметры из app.ini
        [cache]
        ENABLED
        ADAPTER
        INTERVAL
        JSON
        ITEM_TTL
    endnote

    Interface_SC(session_provider, "VirtualSessionProvider", "Сессии в chi")
    Implementation_SC(session_redis, "RedisProvider", "Сессии в Redis: хранение и загрузка данных сессий")
    note right of session_redis
        Использует конфигурационные параметры из app.ini
        [session]
        PROVIDER
        COOKIE_NAME
        COOKIE_PATH
        COOKIE_SECURE
        GC_INTERVAL_TIME
        SESSION_LIFE_TIME
        SAME_SITE
    endnote

    Interface_SC(manager,   "Manager", "Менеджер работы с клиентами")
    Implementation_SC(redis_manager,   "RedisManager", "Менеджер работы с клиентами Redis")

    note right of redis_manager
         Использует конфигурационные параметры из app.ini
        [queue]/[cache]/[session]
        REDIS_PING_RETRY_COUNT
        REDIS_PING_RETRY_INTERVAL
        REDIS_SCHEME
        REDIS_ADDR
        REDIS_ADDRS
        REDIS_HOST
        REDIS_PORT
        REDIS_SOCKET
        REDIS_DB
        REDIS_USERNAME
        REDIS_PASSWORD
        REDIS_CLIENT_NAME
        REDIS_TIMEOUT
        REDIS_DIAL_TIMEOUT
        REDIS_READ_TIMEOUT
        REDIS_WRITE_TIMEOUT
        REDIS_POOL_SIZE
        REDIS_MIN_IDLE_CONNS
        REDIS_POOL_TIMEOUT
        REDIS_IDLE_TIMEOUT
        REDIS_MAX_RETRIES
        REDIS_MIN_RETRY_BACKOFF
        REDIS_MAX_RETRY_BACKOFF
        REDIS_MAX_REDIRECTS
        REDIS_READ_ONLY
        REDIS_ROUTE_BY_LATENCY
        REDIS_ROUTE_RANDOMLY
        REDIS_MASTER_NAME
        REDIS_SENTINEL_USERNAME
        REDIS_SENTINEL_PASSWORD
        REDIS_SKIP_VERIFY
        REDIS_INSECURE_SKIP_VERIFY
    endnote

    Service_SC(queue_manager,   "Manager", "Менеджер работы с очередями")

    Interface_SC(worker_pool,   "WorkerPoolQueue", "Структура для работы очереди")
    Implementation_SC(queue_redis,  "baseRedis", "Очереди в Redis: список + множество для уникальности")

    note right of queue_redis
        [queue]
        TYPE
        DATADIR
        LENGTH
        BATCH_LENGTH
        QUEUE_NAME
        SET_NAME
        MAX_WORKERS
    endnote
}

Redis_Component(redis_storage)

Rel(sc_app, cache, "Использует кэширование")
Rel(sc_app, session_provider, "Использует сессии")
Rel(sc_app, queue_manager, "Использует очереди")
Rel(cache, cache_redis, "Использует")

Rel(queue_manager, worker_pool, "Создает")


' --- Централизованный доступ к Redis ---

Rel(cache_redis,   manager,     "Создает/получает redis-клиента")
Rel(manager, redis_manager, "Получает redis-клиент")
Rel(session_provider, session_redis,     "Реализация redis-провайдера")

Rel(redis_manager, redis_storage, "Создаёт и использует redis.UniversalClient", "go-redis/v9")

' --- Использование Redis из модулей ---

Rel(session_redis, manager, "Получает redis-клиент")
Rel(queue_redis, manager, "Получает redis-клиент")
Rel(worker_pool, queue_redis,  "Реализация redis-очереди")

@enduml
