export const CONVERTER_OPTIONS = Object.freeze({
  folderStrategy: 'Tags',
  includeAuthInfoInExample: false,
  requestNameSource: 'Summary',
});

export const DEFAULT_GENERATION_POLICY = Object.freeze({
  auth: Object.freeze({
    type: 'basic',
    usernameVariable: 'basicAuthUsername',
    passwordVariable: 'basicAuthPassword',
  }),
  removeTopLevelVariables: true,
  removeSwaggerPath: true,
});

export const SURFACES = Object.freeze([
  {
    id: 'v2',
    bundlePath: 'api/openapi/http/v2/openapi_http_v2_bundle.yaml',
    outputDir: 'postman/generated/v2',
    collectionPrefix: 'SourceControl API v2',
    policy: DEFAULT_GENERATION_POLICY,
    folderNameOverrides: {
      admin: 'Admin',
      metrics: 'Metrics',
      projects: 'Projects',
      repos: 'Repository',
      tenants: 'Tenants',
      webhooks: 'Webhooks',
    },
  },
  {
    id: 'v3',
    bundlePath: 'api/openapi/http/v3/openapi_http_v3_bundle.yaml',
    outputDir: 'postman/generated/v3',
    collectionPrefix: 'SourceControl API v3',
    policy: DEFAULT_GENERATION_POLICY,
    folderNameOverrides: {
      admin: 'Admin',
      archive: 'Archive',
      branches: 'Branch',
      branch_protections: 'BranchProtection',
      cache: 'Cache',
      comments: 'Comments',
      commits: 'Commits',
      commit_statuses: 'CommitStatuses',
      compare: 'Compare',
      external_metrics: 'RepoMetrics',
      files: 'Content',
      privileges: 'Privileges',
      pulls: 'PR',
      prupstream: 'PRUpstream',
      repos: 'Repos',
      review_settings: 'ReviewSettings',
      sonar: 'Sonar',
      user: 'User',
      users: 'Users',
    },
  },
  {
    id: 'ui',
    bundlePath: 'api/openapi/ui/openapi_ui_bundle.yaml',
    outputDir: 'postman/generated/ui',
    collectionPrefix: 'SourceControl UI API',
    policy: DEFAULT_GENERATION_POLICY,
    folderNameOverrides: {
      access: 'Access',
      attachments: 'Attachments',
      branches: 'Branches',
      configuration: 'Configuration',
      configurations: 'Configuration',
      diff: 'Diff',
      labels: 'Labels',
      metrics: 'Metrics',
      milestones: 'Milestones',
      projects: 'Projects',
      pulls: 'Pulls',
      repository: 'Repository',
      repos: 'Repository',
      tags: 'Tags',
      template: 'Template',
      topics: 'Topics',
      users: 'Users',
    },
  },
  {
    id: 'system',
    bundlePath: 'api/openapi/system/openapi_system_bundle.yaml',
    outputDir: 'postman/generated/system',
    collectionPrefix: 'SourceControl Health API',
    policy: DEFAULT_GENERATION_POLICY,
    folderNameOverrides: {
      system: 'System',
    },
  },
]);
